version: 2
jobs:
  rails-test-suite:
    docker:
      - image: circleci/ruby:2.3
        environment:
          RAILS_ENV: test
          DATABASE_URL: postgresql://root@localhost/transitland_datastore_test
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: transitland_datastore_test
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Run tests
          command: bundle exec rspec -r rspec_junit_formatter --format RspecJunitFormatter -o $CIRCLE_TEST_REPORTS/rspec/junit.xml
      # - run:
      #     name: Run profile
      #     command: mkdir -p $CIRCLE_ARTIFACTS/profiling && bundle exec rake profile:import:nycdot[$CIRCLE_ARTIFACTS/profiling]
  build-container-image:
    machine: true
    steps:
      - setup_remote_docker
      - checkout
      - run: docker build -t transitland-datastore .
      - run: docker tag transitland-datastore:${CIRCLE_TAG} ${TRANSITLAND_AWS_ECR}/transitland-datastore:${CIRCLE_TAG}
      - run: docker push ${TRANSITLAND_AWS_ECR}/transitland-datastore:${CIRCLE_TAG}
workflows:
  version: 2
  in-progress-development:
    jobs:
      - rails-test-suite:
          filters:
            tags:
              ignore: /^v.*/
  ready-for-container-image:
    jobs:
      - build-container-image:
          requires:
            - rails-test-suite
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
