TRANSITLAND_DATASTORE_AUTH_TOKEN: iamallowedtotouchthis
SIDEKIQ_DASHBOARD_USERNAME: onlyneedonproduction
SIDEKIQ_DASHBOARD_PASSWORD: onlyneedonproduction
TRANSITLAND_FEED_REGISTRY_PATH: <%= Rails.root.join('tmp', 'transitland-feed-registry') %>
TRANSITLAND_FEED_DATA_PATH: <%= Rails.root.join('tmp', 'transitland-feed-data') %>
TRANSITLAND_DATASTORE_HOST: http://localhost:3000
AUTO_CONFLATE_STOPS_WITH_OSM: 'true'
TYR_AUTH_TOKEN: 'get one from mapzen.com/developers'
