ADMIN_USERNAME: onlyneedonproduction
ADMIN_PASSWORD: onlyneedonproduction
TRANSITLAND_DATASTORE_HOST: http://localhost:3000
AUTO_CONFLATE_STOPS_WITH_OSM: 'false'
MAX_HOURS_SINCE_LAST_CONFLATE: '84'
TYR_AUTH_TOKEN: 'get one from mapzen.com/developers'
ATTACHMENTS_S3_REGION: 'us-east-1'
ATTACHMENTS_S3_BUCKET: 'name of an S3 bucket'
AWS_ACCESS_KEY_ID: 'xxxxxxxxx'
AWS_SECRET_ACCESS_KEY: 'xxxxxx'
RUN_GOOGLE_VALIDATOR: 'false'
RUN_CONVEYAL_VALIDATOR: 'false'
FEED_INFO_CACHE_EXPIRATION: '14400'
AUTO_FETCH_FEED_VERSION: 'true'
GTFS_TMPDIR_BASEPATH: null
ENQUEUE_NEXT_FEED_VERSIONS_MAX: 0
SMTP_ADDRESS: smtp.sparkpostmail.com
SMTP_PORT: '587'
SMTP_USER_NAME: SMTP_Injection
SMTP_PASSWORD: XXX
PG_TIMEOUT: 120000
