TRANSITLAND_DATASTORE_AUTH_TOKEN: iamallowedtotouchthis
SIDEKIQ_DASHBOARD_USERNAME: onlyneedonproduction
SIDEKIQ_DASHBOARD_PASSWORD: onlyneedonproduction
TRANSITLAND_FEED_REGISTRY_PATH: <%= Rails.root.join('tmp', 'transitland-feed-registry') %>
TRANSITLAND_FEED_DATA_PATH: <%= Rails.root.join('tmp', 'transitland-feed-data') %>
DATASTORE_PROTOCOL: http
DATASTORE_HOST: localhost
DATASTORE_PORT: '3000'
AUTO_CONFLATE_STOPS_WITH_OSM: 'true'
TYR_API_KEY: 'get one from mapzen.com/developers'
